# Generated by Django 5.0.4 on 2024-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
