# Generated by Django 5.0.4 on 2024-04-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='specialization',
        ),
    ]
